language: php

php:
    - 5.5
    - 5.4

env:
    - RUN=phpunit
    - RUN=vendor/bin/phpunit

script: ${RUN}

before_script:
    - "composer selfupdate"
    - "composer install --prefer-dist --verbose"